stages:
  - test
  - build
  - deploy

test:
  image: rust:latest
  stage: test
  before_script:
    - rustup component add rustfmt clippy
  script:
    - cargo test -p dot2shader
    - cargo fmt --all -- --check
    - cargo clippy --release

wasm-pack:
  image: drydockapp/wasm-pack
  stage: build
  script:
    - mkdir -p built-page
    - export RUSTFLAGS=--cfg=web_sys_unstable_apis
    - cd dot2shader-gui
    - wasm-pack build --target web
    - mv resources/index.html resources/favicon.ico pkg/dot2shader_gui.js pkg/dot2shader_gui_bg.wasm ../built-page/
  artifacts:
    paths:
      - built-page

doc:
  image: rust:latest
  stage: build
  script:
    - cargo doc --no-deps
    - mv target/doc libdoc
  artifacts:
    paths:
      - libdoc

pages:
  image: drydockapp/wasm-pack
  stage: deploy
  script:
    - mkdir -p public
    - mv built-page/* public/
    - mv libdoc public/
  artifacts:
    paths:
      - public
  only:
      - main
