pages:
  image: drydockapp/wasm-pack
  stage: deploy
  script:
    - export RUSTFLAGS=--cfg=web_sys_unstable_apis
    - mkdir -p public
    - cd dot2shader-gui
    - wasm-pack build --target web
    - cp resources/index.html resources/favicon.ico pkg/dot2shader_gui.js pkg/dot2shader_gui_bg.wasm ../public/
    - cd ..
    - cargo doc --no-deps
    - cp -r target/doc public/libdoc
  artifacts:
    paths:
    - public
  only:
    - main
